# app/config/services.yml
services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    AppBundle\Controller\:
        resource: '../../src/AppBundle/Controller'
        tags: ['controller.service_arguments']

    #
    # Handlers - Command
    #
    Application\Command\User\RegisterHandler: ~

    #
    # Handlers - Query
    #
    Application\Query\User\DetailsHandler: ~

    #
    # Repositories
    #
    Infrastructure\Repository\UserRepository: ~
