# app/config/services.yml
services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    AppBundle\Controller\:
        resource: '../../src/AppBundle/Controller'
        tags: ['controller.service_arguments']

    #
    # Handlers - Command
    #
    Application\Command\User\RegisterHandler: ~

    Application\Command\User\SendMailHandler: ~

    Application\Command\User\PostLoginHandler: ~

    #
    # Handlers - Query
    #
    Application\Query\User\DetailsHandler: ~

    #
    # Repositories
    #
    Infrastructure\Repository\UserRepository: ~

    #
    # Adapter
    #
    Infrastructure\Adapter\SerializerAdapter: ~

    #
    # ParamConverter
    #
    AppBundle\ParamConverter\User\UserIdParamConverter:
        tags:
            - { name: 'request.param_converter', priority: 2, converter: 'participant_type_view_param_converter' }

    #
    # Console Command
    #
    Infrastructure\Command\SendMail:
        tags:
            - { name: console.command }