# app/config/services.yml
services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    AppBundle\Controller\:
        resource: '../../src/AppBundle/Controller/*'
        public: true

    #
    # Handlers
    #
    Application\Command\User\RegisterHandler: ~

    #
    # Repositories
    #
    Infrastructure\Repository\UserRepository: ~
