Domain\Model\User:
    type: entity
    table: user
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        email:
            type: string
        password:
            type: string
        name:
            type: string
        profileurl:
            type: string
        lastlogin:
            type: datetime
        creationdate:
            type: datetime
    oneToMany:
        commissions:
            targetEntity: Domain\Model\Commission
            mappedBy: idUser
            cascade: ["persist"]
