Domain\Dto\User\RegisterDto:
    properties:
        email:
            - NotBlank: ~
        password:
            - NotBlank: ~
        name:
            - NotBlank: ~
        profileUrl:
            - NotBlank: ~
        lastLogin:
            - NotBlank: ~
            - DateTime: ~
        creationDate:
            - NotBlank: ~
            - DateTime: ~